version: "3.8"

services:
  db:
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stackoverfaux-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stackoverfaux_network

  backend:
    build:
      context: ./stackoverfaux-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/stackoverfaux-db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - stackoverfaux_network

volumes:
  postgres_data:

networks:
  stackoverfaux_network:
    driver: bridge
